In [1]:
import pandas as pd
import numpy as np
import json
from sqlalchemy import create_engine
import dotenv
dotenv.load_dotenv()

# 1. เชื่อมต่อกับฐานข้อมูล
# เปลี่ยน user, password, host, port, db_name ให้ตรงกับของคุณ
engine = create_engine(f'postgresql://postgres:{dotenv.dotenv_values().get("PASSWORD")}@localhost:5432/{dotenv.dotenv_values().get("DB_NAME")}')

In [36]:
df_prolang = pd.read_sql('select * from prolang', engine)
for i in range(2020,2026):
    with open(f'SO_survey_{i}_desire.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    df = pd.DataFrame(data)
    # 1. Split ภาษาออกเป็น List
    df['Language'] = df['Language'].str.split('/')

    # 2. หาร count ด้วยจำนวนสมาชิกใน List
    # ใช้ .str.len() เพื่อดูว่ามีกี่ภาษาในแถวนั้น
    df['count'] = df['count'] / df['Language'].str.len()
    df['count'] = df['count'].astype('int64')

    # 3. Explode ให้กระจายเป็นแถวละภาษา
    df_clean = df.explode('Language')
    def mapping(val):
        if val == 'VISUAL BASIC (.NET)':
            return 'VB.NET'
        elif val == 'SHELL (ALL SHELLS)':
            return 'SHELL'
        return val
    df_clean['Language'] = df_clean['Language'].apply(mapping)
    df_survey = pd.merge(df_clean, df_prolang, left_on='Language', right_on='prolangname', how='left')
    df_survey.drop_duplicates(keep='first', inplace=True)
    df_survey = df_survey[['prolangid','count','year_of_survey']].rename(columns={'count':'total','year_of_survey':'year'})
    df_survey['year'] = df_survey['year'].astype(str)
    df_survey.sort_values(by='prolangid',inplace=True)
    print(df_survey.info())
    display(df_survey)
    df_survey.to_sql('so_survey', engine, if_exists='append', index=False)

<class 'pandas.DataFrame'>
Index: 28 entries, 0 to 27
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   prolangid  28 non-null     int64
 1   total      28 non-null     int64
 2   year       28 non-null     str
dtypes: int64(2), str(1)
memory usage: 896.0 bytes
None

    prolangid  total  year
0           4   4938  2020
1           5   7818  2020
4           6  12182  2020
5           7  27348  2020
6           8  19512  2020
11         12  20771  2020
7          13   9484  2020
8          22  25210  2020
9          24   5992  2020
10         25  20771  2020
12         26  26528  2020
13         27  52376  2020
14         28   3322  2020
15         29  19150  2020
16         37   3050  2020
17         39   2300  2020
18         40  14212  2020
3          41   7818  2020
19         43  53364  2020
20         44   8542  2020
21         46   8368  2020
22         47  21126  2020
23         49   6930  2020
2          50   7818  2020
24         52  39940  2020
25         53  11286  2020
26         54  34300  2020
27         55   2110  2020

<class 'pandas.DataFrame'>
Index: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   prolangid  40 non-null     int64
 1   total      40 non-null     int64
 2   year       40 non-null     str
dtypes: int64(2), str(1)
memory usage: 1.2 KB
None

    prolangid  total  year
0           3   1136  2021
1           4   7156  2021
2           5  14043  2021
4           6  19404  2021
5           7  35998  2021
6           8  30498  2021
7           9   4826  2021
8          10    618  2021
9          11   1580  2021
19         12  29353  2021
10         13  14036  2021
11         14   1950  2021
12         15   6748  2021
13         16   2758  2021
14         17   4314  2021
15         22  31576  2021
16         23   2354  2021
17         24   6906  2021
18         25  29353  2021
20         26  34444  2021
21         27  74016  2021
22         28   4890  2021
23         29  21382  2021
24         30   3026  2021
25         32   3124  2021
26         36  48200  2021
27         37   2800  2021
28         39   2350  2021
29         40  17704  2021
30         41   9792  2021
31         43  69858  2021
32         44   8030  2021
33         46   9884  2021
34         47  31730  2021
35         49   6330  2021
3          50  14043  2021
36         52  53262  2021
37         53  12706  2021
38         54  53810  2021
39         55   2138  2021

<class 'pandas.DataFrame'>
Index: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   prolangid  44 non-null     int64
 1   total      44 non-null     int64
 2   year       44 non-null     str
dtypes: int64(2), str(1)
memory usage: 1.4 KB
None

    prolangid  total  year
0           3   1216  2022
1           4   6092  2022
2           5  13242  2022
4           6  15712  2022
5           7  31362  2022
6           8  23792  2022
7           9   3876  2022
8          10    692  2022
9          11   1020  2022
20         12  25423  2022
10         13  12166  2022
11         14   3326  2022
12         15   6578  2022
13         16   2448  2022
14         17   3894  2022
15         19    878  2022
16         22  31000  2022
17         23   2074  2022
18         24   5922  2022
19         25  25423  2022
21         26  26690  2022
22         27  63102  2022
23         28   4442  2022
24         29  18632  2022
25         30   2480  2022
26         31   4780  2022
27         32   2118  2022
28         37   1754  2022
29         38   1478  2022
30         39   1868  2022
31         40  14650  2022
32         41   9400  2022
33         43  58700  2022
34         44   5868  2022
35         46   7814  2022
36         47  34226  2022
37         48    756  2022
38         49   4902  2022
3          50  13242  2022
39         51   5212  2022
40         52  49608  2022
41         53  10142  2022
42         54  52100  2022
43         55   1846  2022

<class 'pandas.DataFrame'>
Index: 53 entries, 0 to 51
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   prolangid  53 non-null     int64
 1   total      53 non-null     int64
 2   year       53 non-null     str
dtypes: int64(2), str(1)
memory usage: 1.7 KB
None

    prolangid  total  year
0           1   1320  2023
1           2    962  2023
2           3    814  2023
3           4   7660  2023
4           5  18279  2023
6           6  20058  2023
7           7  37186  2023
8           8  28462  2023
9           9   3820  2023
10         10    790  2023
11         11   1198  2023
24         12  29928  2023
12         13  12112  2023
13         14   3896  2023
14         15   7760  2023
15         16   2832  2023
16         17   4202  2023
17         18    362  2023
18         19   1016  2023
19         20   3130  2023
20         22  35986  2023
21         23   2442  2023
22         24   6720  2023
23         25  29928  2023
25         26  28768  2023
26         27  69972  2023
27         28   4368  2023
28         29  21116  2023
29         30   3410  2023
30         31   8164  2023
31         32   2278  2023
32         35   1622  2023
33         37   1908  2023
34         38   2166  2023
35         39   2156  2023
36         40  16028  2023
37         41  12284  2023
38         42   1116  2023
39         43  69430  2023
40         44   6136  2023
41         45    558  2023
42         46   8586  2023
43         47  53420  2023
44         48    710  2023
45         49   5540  2023
5          50  18279  2023
46         51   3194  2023
47         52  59196  2023
48         53  10774  2023
49         54  64512  2023
50         55   1900  2023
52         58   7294  2023
51         60   2700  2023

<class 'pandas.DataFrame'>
Index: 51 entries, 0 to 48
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   prolangid  51 non-null     int64
 1   total      51 non-null     int64
 2   year       51 non-null     str
dtypes: int64(2), str(1)
memory usage: 1.6 KB
None

    prolangid  total  year
0           1   1116  2024
1           2    778  2024
2           4   6014  2024
3           5  13744  2024
5           6  16550  2024
6           7  25842  2024
7           8  21746  2024
8           9   2662  2024
9          10    798  2024
10         11    814  2024
22         12  20721  2024
11         13   7418  2024
12         14   1188  2024
13         15   5790  2024
14         16   2274  2024
15         17   2544  2024
16         19    974  2024
17         20   3334  2024
18         22  27674  2024
19         23   1698  2024
20         24   4442  2024
21         25  20721  2024
23         26  21336  2024
24         27  47548  2024
25         28   2526  2024
26         29  14758  2024
27         30   2510  2024
28         31   6644  2024
29         32   1890  2024
30         33   2078  2024
31         35    998  2024
32         37   1372  2024
33         38   2160  2024
34         39   1588  2024
35         40  11490  2024
36         41   8574  2024
37         42    792  2024
38         43  50094  2024
39         44   4354  2024
40         46   5548  2024
41         47  34464  2024
42         49   3580  2024
4          50  13744  2024
43         51   1914  2024
44         52  44800  2024
45         53   7754  2024
46         54  40478  2024
47         55   1446  2024
49         57    496  2024
50         58   7376  2024
48         60   1924  2024

<class 'pandas.DataFrame'>
Index: 44 entries, 0 to 42
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   prolangid  44 non-null     int64
 1   total      44 non-null     int64
 2   year       44 non-null     str
dtypes: int64(2), str(1)
memory usage: 1.4 KB
None

    prolangid  total  year
0           1   1022  2025
1           4   4308  2025
2           5   8662  2025
4           6   9096  2025
5           7  12234  2025
6           8  10486  2025
7          10    806  2025
19         12  10661  2025
8          13   3306  2025
9          14   1126  2025
10         15   3636  2025
11         16   1912  2025
12         17   1816  2025
13         19    794  2025
14         20   2144  2025
15         21   1944  2025
16         22  14828  2025
17         23   1212  2025
18         25  10661  2025
20         26   9962  2025
21         27  21162  2025
22         29   7572  2025
23         30   2272  2025
24         31   4778  2025
25         32   1234  2025
26         33   1662  2025
27         34   1144  2025
28         38   1728  2025
29         39   1402  2025
30         40   5746  2025
31         41   6028  2025
32         42    828  2025
33         43  24838  2025
34         44   2616  2025
35         46   3174  2025
36         47  18524  2025
37         49   1848  2025
3          50   8662  2025
38         52  22514  2025
39         53   4066  2025
40         54  20198  2025
41         55    962  2025
43         58   4830  2025
42         60   1154  2025