In [43]:
import pandas as pd
import numpy as np
import json

with open('Adzuna_Cleaned.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
df = pd.DataFrame(data)
df = df.explode('languages')
df.dropna(subset=['languages'], inplace=True)
df.dropna(subset=['company'], inplace=True)
df.rename(columns={'languages': 'Language'}, inplace=True)
print(df.info())
display(df.tail())

<class 'pandas.DataFrame'>
Index: 1951 entries, 0 to 4498
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        1951 non-null   int64
 1   company   1951 non-null   str
 2   title     1951 non-null   str
 3   year      1951 non-null   int64
 4   Language  1951 non-null   str
dtypes: int64(2), str(3)
memory usage: 91.5 KB
None

,id,company,title,year,Language
4440,5608834120,SS&C,Implementation Manager PA25Q4IMJH022,2026,C++
4441,5608834038,Aryza,Software Engineer,2026,C#
4492,5607449365,BNY Mellon,"FX eTrading Java Back-End Engineer, Vice Presi...",2026,Java
4493,5607449243,Google,"Software Engineer III, Embedded, Pixel Graphics",2026,C++
4498,5607448019,Sporty Group,Python Engineer,2026,Python

In [2]:
from sqlalchemy import create_engine
import dotenv
dotenv.load_dotenv()

# 1. เชื่อมต่อกับฐานข้อมูล
# เปลี่ยน user, password, host, port, db_name ให้ตรงกับของคุณ
engine = create_engine(f'postgresql://postgres:{dotenv.dotenv_values().get("PASSWORD")}@localhost:5432/{dotenv.dotenv_values().get("DB_NAME")}')

company Insert

In [30]:
df_company = df[['company']].drop_duplicates(keep='first')
df_company.rename(columns={'company': 'companyname'}, inplace=True)
print(df_company.info())
display(df_company.head())

<class 'pandas.DataFrame'>
Index: 553 entries, 0 to 4498
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   companyname  553 non-null    str
dtypes: str(1)
memory usage: 8.6 KB
None

                companyname
0              Boost Talent
4     Reality Solutions Ltd
13  Spectrum IT Recruitment
16         Joseph Harry Ltd
24      The Portfolio Group

In [31]:
df_company.to_sql('company', engine, if_exists='append', index=False)

553

Job Insert

In [56]:
df_job = df[['title', 'company', 'year']].copy()
df_company = pd.read_sql('SELECT * FROM company', engine)
df_job.rename(columns={'title': 'name', 'company': 'company_name'}, inplace=True)
df_job = df_job.merge(df_company, left_on='company_name', right_on='companyname', how='left')
df_job = df_job[['name', 'year', 'companyid']].rename(columns={'name':'jobname'})
df_job = df_job.drop_duplicates(keep='first')
#df_job['companyid'] = df_job['companyid'].astype(int)
print(df_job.info())
display(df_job.tail())

<class 'pandas.DataFrame'>
Index: 1035 entries, 0 to 1950
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   jobname    1035 non-null   str
 1   year       1035 non-null   int64
 2   companyid  1035 non-null   int64
dtypes: int64(2), str(1)
memory usage: 32.3 KB
None

                                                jobname  year  companyid
1946               Implementation Manager PA25Q4IMJH022  2026        598
1947                                  Software Engineer  2026       1135
1948  FX eTrading Java Back-End Engineer, Vice Presi...  2026       1136
1949    Software Engineer III, Embedded, Pixel Graphics  2026        844
1950                                    Python Engineer  2026       1137

In [39]:
df_job.to_sql('job', engine, if_exists='append', index=False)

35

job_from_source Insert

In [44]:
source = {
    'sourcename': 'Adzuna',
    'url': 'https://www.Adzuna.com/',
}
df_source = pd.DataFrame([source])
print(df_source.info())
display(df_source.head())

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sourcename  1 non-null      str
 1   url         1 non-null      str
dtypes: str(2)
memory usage: 148.0 bytes
None

  sourcename                      url
0     Adzuna  https://www.Adzuna.com/

In [45]:
df_source.to_sql('job_source', engine, if_exists='append', index=False)

1

In [47]:
job_from_source = pd.read_sql('SELECT * FROM job where jobid > 2112', engine)
job_from_source['sourceid'] = 3
job_from_source = job_from_source[['jobid', 'sourceid']]
print(job_from_source.info())
display(job_from_source)

<class 'pandas.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   jobid     1035 non-null   int64
 1   sourceid  1035 non-null   int64
dtypes: int64(2)
memory usage: 16.3 KB
None

      jobid  sourceid
0      2113         3
1      2114         3
2      2115         3
3      2116         3
4      2117         3
...     ...       ...
1030   3143         3
1031   3144         3
1032   3145         3
1033   3146         3
1034   3147         3

[1035 rows x 2 columns]

In [48]:
job_from_source.to_sql('job_from_source', engine, if_exists='append', index=False)

35

job_prolang Insert

In [83]:
df_jobs = df[['title', 'Language','company']].drop_duplicates(keep='first').copy()
df_company_query = pd.read_sql('select * from company where companyid > 459',engine)
df_job_company = pd.merge(df_jobs,df_company_query,left_on='company',right_on='companyname',how='left')
print(df_jobs.info())
display(df_jobs)

<class 'pandas.DataFrame'>
Index: 1673 entries, 0 to 4498
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     1673 non-null   str
 1   Language  1673 non-null   str
 2   company   1673 non-null   str
dtypes: str(3)
memory usage: 52.3 KB
None

,title,Language,company
0,SC Cleared SCALA Developer/Remote - Inside IR35,Scala,Boost Talent
4,Software Developer (.NET / SQL),C#,Reality Solutions Ltd
4,Software Developer (.NET / SQL),SQL,Reality Solutions Ltd
13,Technical Lead Developer - Full Stack,JavaScript,Spectrum IT Recruitment
13,Technical Lead Developer - Full Stack,TypeScript,Spectrum IT Recruitment
...,...,...,...
4440,Implementation Manager PA25Q4IMJH022,C++,SS&C
4441,Software Engineer,C#,Aryza
4492,"FX eTrading Java Back-End Engineer, Vice Presi...",Java,BNY Mellon
4493,"Software Engineer III, Embedded, Pixel Graphics",C++,Google
4498,Python Engineer,Python,Sporty Group

In [94]:
df_job_company.rename(columns={'title':'jobname'},inplace=True)
display(df_job_company)
df_job_query = pd.read_sql('select * from job where jobid > 2112',engine)
df_job_with_company = pd.merge(df_job_company,df_job_query,on=['jobname','companyid'],how='inner')
print(df_job_with_company.info())
display(df_job_with_company)

,jobname,Language,company,companyid,companyname
0,SC Cleared SCALA Developer/Remote - Inside IR35,Scala,Boost Talent,585,Boost Talent
1,Software Developer (.NET / SQL),C#,Reality Solutions Ltd,586,Reality Solutions Ltd
2,Software Developer (.NET / SQL),SQL,Reality Solutions Ltd,586,Reality Solutions Ltd
3,Technical Lead Developer - Full Stack,JavaScript,Spectrum IT Recruitment,587,Spectrum IT Recruitment
4,Technical Lead Developer - Full Stack,TypeScript,Spectrum IT Recruitment,587,Spectrum IT Recruitment
...,...,...,...,...,...
1668,Implementation Manager PA25Q4IMJH022,C++,SS&C,598,SS&C
1669,Software Engineer,C#,Aryza,1135,Aryza
1670,"FX eTrading Java Back-End Engineer, Vice Presi...",Java,BNY Mellon,1136,BNY Mellon
1671,"Software Engineer III, Embedded, Pixel Graphics",C++,Google,844,Google
1672,Python Engineer,Python,Sporty Group,1137,Sporty Group

<class 'pandas.DataFrame'>
RangeIndex: 1673 entries, 0 to 1672
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   jobname      1673 non-null   str
 1   Language     1673 non-null   str
 2   company      1673 non-null   str
 3   companyid    1673 non-null   int64
 4   companyname  1673 non-null   str
 5   jobid        1673 non-null   int64
 6   year         1673 non-null   str
dtypes: int64(2), str(5)
memory usage: 91.6 KB
None

,jobname,Language,company,companyid,companyname,jobid,year
0,SC Cleared SCALA Developer/Remote - Inside IR35,Scala,Boost Talent,585,Boost Talent,2113,2026
1,Software Developer (.NET / SQL),C#,Reality Solutions Ltd,586,Reality Solutions Ltd,2114,2026
2,Software Developer (.NET / SQL),SQL,Reality Solutions Ltd,586,Reality Solutions Ltd,2114,2026
3,Technical Lead Developer - Full Stack,JavaScript,Spectrum IT Recruitment,587,Spectrum IT Recruitment,2115,2026
4,Technical Lead Developer - Full Stack,TypeScript,Spectrum IT Recruitment,587,Spectrum IT Recruitment,2115,2026
...,...,...,...,...,...,...,...
1668,Implementation Manager PA25Q4IMJH022,C++,SS&C,598,SS&C,3143,2026
1669,Software Engineer,C#,Aryza,1135,Aryza,3144,2026
1670,"FX eTrading Java Back-End Engineer, Vice Presi...",Java,BNY Mellon,1136,BNY Mellon,3145,2026
1671,"Software Engineer III, Embedded, Pixel Graphics",C++,Google,844,Google,3146,2026
1672,Python Engineer,Python,Sporty Group,1137,Sporty Group,3147,2026

In [104]:
df_prolang = pd.read_sql('SELECT * FROM prolang', engine)
df_job_with_company['Language'] = df_job_with_company['Language'].str.upper()
# รวมชื่อที่เป็นชื่อเล่น/ชื่อย่อ ให้เป็นมาตรฐานเดียวกัน
mapping = {
    'GOLANG': 'GO',
    'ASSEMBLY LANGUAGE': 'ASSEMBLY',
    'PL/SQL': 'SQL'
}
df_job_with_company['Language'] = df_job_with_company['Language'].replace(mapping)
df_job_skill = pd.merge(df_job_with_company,df_prolang,how='left',left_on='Language',right_on='prolangname')
df_job_prolang = df_job_skill[['jobid','prolangid']].drop_duplicates(keep='first')
print(df_job_prolang.info())
display(df_job_prolang)

<class 'pandas.DataFrame'>
Index: 1664 entries, 0 to 1672
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   jobid      1664 non-null   int64
 1   prolangid  1664 non-null   int64
dtypes: int64(2)
memory usage: 39.0 KB
None

      jobid  prolangid
0      2113         49
1      2114          7
2      2114         52
3      2115         27
4      2115         54
...     ...        ...
1668   3143          8
1669   3144          7
1670   3145         26
1671   3146          8
1672   3147         43

[1664 rows x 2 columns]

In [105]:
df_job_prolang.to_sql('job_prolang', engine, if_exists='append', index=False)

664