In [22]:
import pandas as pd
import numpy as np
import json

with open('Final_Final_HackerNews_Cleaned.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
df = pd.DataFrame(data)
df['Actual_Post_Year'] = df['Actual_Post_Year'].astype(str)
print(df.info())
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 24497 entries, 0 to 24496
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   clean_title       24497 non-null  str
 1   language          24497 non-null  str
 2   Scrap_Year        24497 non-null  int64
 3   Actual_Post_Year  24497 non-null  str
dtypes: int64(1), str(3)
memory usage: 765.7 KB
None

,clean_title,language,Scrap_Year,Actual_Post_Year
0,Uv is the best thing to happen to the Python e...,Python,2026,2025
1,A from-scratch tour of Bitcoin in Python,Python,2026,2021
2,Python 3.13 Gets a JIT,Python,2026,2024
3,I built a hardware processor that runs Python,Python,2026,2025
4,Prettymaps: Small Python library to draw custo...,Python,2026,2021

In [14]:
from sqlalchemy import create_engine
import dotenv
dotenv.load_dotenv()

# 1. เชื่อมต่อกับฐานข้อมูล
# เปลี่ยน user, password, host, port, db_name ให้ตรงกับของคุณ
engine = create_engine(f'postgresql://postgres:{dotenv.dotenv_values().get("PASSWORD")}@localhost:5432/{dotenv.dotenv_values().get("DB_NAME")}')

Hackernews_source Insert

In [16]:
df_hackernews_source = df[['clean_title','Actual_Post_Year']].rename(columns={'clean_title':'title','Actual_Post_Year':'year'}).copy()
df_hackernews_source.drop_duplicates(keep='first',inplace=True)
print(df_hackernews_source.info())
display(df_hackernews_source)

<class 'pandas.DataFrame'>
Index: 23331 entries, 0 to 24496
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   23331 non-null  str
 1   year    23331 non-null  int64
dtypes: int64(1), str(1)
memory usage: 546.8 KB
None

                                                   title  year
0      Uv is the best thing to happen to the Python e...  2025
1               A from-scratch tour of Bitcoin in Python  2021
2                                 Python 3.13 Gets a JIT  2024
3          I built a hardware processor that runs Python  2025
4      Prettymaps: Small Python library to draw custo...  2021
...                                                  ...   ...
24492  XID – Dependency-Free Unique ID Generator in O...  2025
24493  Stb_zip – header-only C ZIP parser, zero depen...  2025
24494                           Resources for Learning C  2021
24495  OpenAI-C – A lightweight OpenAI Chat API clien...  2025
24496  One Career, One Language: Could Rust Be This G...  2025

[23331 rows x 2 columns]

In [18]:
df_hackernews_source.to_sql('hackernews_source',engine, if_exists='append', index=False)

331

Skill Insert 24497

In [31]:
df_hackernews = pd.read_sql('select * from hackernews_source', engine)
df_hackernews_id = pd.merge(df[['clean_title','language','Actual_Post_Year']], df_hackernews
                                , left_on=['clean_title','Actual_Post_Year'], right_on=['title','year'], how='left')
df_hackernews_id['language'] = df_hackernews_id['language'].str.upper()
df_prolang = pd.read_sql('select * from prolang', engine)
df_hackernews_prolang = pd.merge(df_hackernews_id, df_prolang, left_on='language', right_on='prolangname', how='left')
df_hackernews_prolang = df_hackernews_prolang[['postid','prolangid']]
print(df_hackernews_prolang.info())
display(df_hackernews_prolang)

<class 'pandas.DataFrame'>
RangeIndex: 24497 entries, 0 to 24496
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   postid     24497 non-null  int64
 1   prolangid  24497 non-null  int64
dtypes: int64(2)
memory usage: 382.9 KB
None

       postid  prolangid
0           1         43
1           2         43
2           3         43
3           4         43
4           5         43
...       ...        ...
24492   23327          6
24493   23328          6
24494   23329          6
24495   23330          6
24496   23331          6

[24497 rows x 2 columns]

In [32]:
df_hackernews_prolang.to_sql('prolang_hacker', engine, if_exists='append', index=False)

497