In [17]:
import pandas as pd
import numpy as np
import json

with open('cleaned_jobs.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
df = pd.DataFrame(data)
df = df.explode('Language')
print(df.info())
display(df.head())

<class 'pandas.DataFrame'>
Index: 968 entries, 0 to 466
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   URL        968 non-null    str
 1   Company    968 non-null    str
 2   Job Title  968 non-null    str
 3   Date       968 non-null    int64
 4   Language   968 non-null    str
dtypes: int64(1), str(4)
memory usage: 45.4 KB
None

,URL,Company,Job Title,Date,Language
0,https://www.jobthai.com/en/job/1003600,บริษัท เอคซเทนด์ ไอที รีซอร์ส จำกัด,System Analyst/ Business Analyst (Contract/Out...,2026,SQL
1,https://www.jobthai.com/en/job/1017656,บริษัท ไทย อกริ ฟู้ดส์ จำกัด (มหาชน),Programmer (ประจำกรุงเทพ ),2026,SQL
2,https://www.jobthai.com/en/job/1051153,"Gosoft (Thailand) Co., Ltd.",Automate Test Lead,2026,SQL
2,https://www.jobthai.com/en/job/1051153,"Gosoft (Thailand) Co., Ltd.",Automate Test Lead,2026,Python
3,https://www.jobthai.com/en/job/1054167,"OGA INTERNATIONAL CO.,LTD",Programmer (ประจำสาขากรุงเทพฯ ),2026,VB.NET

In [10]:
from sqlalchemy import create_engine
import dotenv
dotenv.load_dotenv()

# 1. เชื่อมต่อกับฐานข้อมูล
# เปลี่ยน user, password, host, port, db_name ให้ตรงกับของคุณ
engine = create_engine(f'postgresql://postgres:{dotenv.dotenv_values().get("PASSWORD")}@localhost:5432/{dotenv.dotenv_values().get("DB_NAME")}')

company Insert

In [19]:
df_company = df[['Company']].drop_duplicates().reset_index(drop=True)
df_company.rename(columns={'Company': 'companyname'}, inplace=True)
print(df_company.info())
display(df_company.head())

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   companyname  334 non-null    str
dtypes: str(1)
memory usage: 2.7 KB
None

                            companyname
0   บริษัท เอคซเทนด์ ไอที รีซอร์ส จำกัด
1  บริษัท ไทย อกริ ฟู้ดส์ จำกัด (มหาชน)
2           Gosoft (Thailand) Co., Ltd.
3             OGA INTERNATIONAL CO.,LTD
4          บริษัท ดิจิค เทคโนโลยี จำกัด

In [6]:
df_company.to_sql('company', engine, if_exists='append', index=False)

334

Job Insert

In [4]:
df_job = df[['Job Title', 'Company', 'Date']].copy()
df_company = pd.read_sql('SELECT * FROM company', engine)
df_job.rename(columns={'Job Title': 'name', 'Company': 'company_name', 'Date': 'year'}, inplace=True)
df_job = df_job.merge(df_company, left_on='company_name', right_on='companyname', how='left')
df_job = df_job[['name', 'year', 'companyid']].rename(columns={'name': 'jobname'})
df_job.drop_duplicates(inplace=True)
print(df_job.info())
display(df_job.tail())

<class 'pandas.DataFrame'>
Index: 467 entries, 0 to 967
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   jobname    467 non-null    str
 1   year       467 non-null    int64
 2   companyid  467 non-null    int64
dtypes: int64(2), str(1)
memory usage: 14.6 KB
None

                                    jobname  year  companyid
956  Programmer (ประจำออฟฟิศรามอินทรา กทม.)  2026        457
960                      Software Tester/QA  2026        231
961        Programmer ภาษา Flutter / Golang  2026        458
963                    Programmer/Developer  2026        459
967                         System Engineer  2026        198

In [12]:
df_job.to_sql('job', engine, if_exists='append', index=False)

467

job_from_source Insert

In [13]:
source = {
    'sourcename': 'JobThai',
    'url': 'https://www.jobthai.com/',
}
df_source = pd.DataFrame([source])
print(df_source.info())
display(df_source.head())

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sourcename  1 non-null      str
 1   url         1 non-null      str
dtypes: str(2)
memory usage: 148.0 bytes
None

  sourcename                       url
0    JobThai  https://www.jobthai.com/

In [14]:
df_source.to_sql('job_source', engine, if_exists='append', index=False)

1

In [15]:
df_jobs = pd.read_sql('SELECT * FROM job where jobid > 1645', engine)
df_jobs['sourceid'] = 2
df_jobs = df_jobs[['jobid', 'sourceid']]
print(df_jobs.info())
display(df_jobs.head())

<class 'pandas.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   jobid     467 non-null    int64
 1   sourceid  467 non-null    int64
dtypes: int64(2)
memory usage: 7.4 KB
None

   jobid  sourceid
0   1646         2
1   1647         2
2   1648         2
3   1649         2
4   1650         2

In [16]:
df_jobs.to_sql('job_from_source', engine, if_exists='append', index=False)

467

job_prolang Insert

In [8]:
df_job = df[['Job Title', 'Language','Company']].copy()
df_job.drop_duplicates(inplace=True)
before_job_result = ''
before_company_result = ''
stratnum = 1645
def getjobid(col):
    global before_job_result
    global before_company_result
    global stratnum
    if col['Job Title'] == before_job_result and col['Company'] == before_company_result:
        return stratnum
    before_job_result = col['Job Title']
    before_company_result = col['Company']
    stratnum += 1
    return stratnum
df_job['Job ID'] = df_job[['Job Title', 'Company']].apply(getjobid, axis=1)
print(df_job.info())
display(df_job)

<class 'pandas.DataFrame'>
Index: 968 entries, 0 to 466
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Job Title  968 non-null    str
 1   Language   968 non-null    str
 2   Company    968 non-null    str
 3   Job ID     968 non-null    int64
dtypes: int64(1), str(3)
memory usage: 37.8 KB
None

,Job Title,Language,Company,Job ID
0,System Analyst/ Business Analyst (Contract/Out...,SQL,บริษัท เอคซเทนด์ ไอที รีซอร์ส จำกัด,1646
1,Programmer (ประจำกรุงเทพ ),SQL,บริษัท ไทย อกริ ฟู้ดส์ จำกัด (มหาชน),1647
2,Automate Test Lead,SQL,"Gosoft (Thailand) Co., Ltd.",1648
2,Automate Test Lead,Python,"Gosoft (Thailand) Co., Ltd.",1648
3,Programmer (ประจำสาขากรุงเทพฯ ),VB.NET,"OGA INTERNATIONAL CO.,LTD",1649
...,...,...,...,...
465,Programmer/Developer,VB.NET,Power vision group co. ltd เครือเดียวกับ Human...,2111
465,Programmer/Developer,SQL,Power vision group co. ltd เครือเดียวกับ Human...,2111
465,Programmer/Developer,JavaScript,Power vision group co. ltd เครือเดียวกับ Human...,2111
465,Programmer/Developer,.NET,Power vision group co. ltd เครือเดียวกับ Human...,2111
466,System Engineer,SQL,บริษัท จีเอเบิล จำกัด (มหาชน),2112

In [15]:
df_prolang = pd.read_sql('SELECT * FROM prolang', engine)
df_job['Language'] = df_job['Language'].str.upper()
def set_language(val):
    if val == '.NET':
        return 'C#'
    return val
df_job['Language'] = df_job['Language'].apply(set_language)
df_job_skill = pd.merge(df_job,df_prolang,how='left',left_on='Language',right_on='prolangname')
df_job_prolang = df_job_skill[['Job ID','prolangid']].rename(columns={'Job ID':'jobid'})
print(df_job_prolang.info())
display(df_job_prolang)

<class 'pandas.DataFrame'>
RangeIndex: 968 entries, 0 to 967
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   jobid      968 non-null    int64
 1   prolangid  968 non-null    int64
dtypes: int64(2)
memory usage: 15.3 KB
None

     jobid  prolangid
0     1646         52
1     1647         52
2     1648         52
3     1648         43
4     1649         60
..     ...        ...
963   2111         60
964   2111         52
965   2111         27
966   2111          7
967   2112         52

[968 rows x 2 columns]

In [16]:
df_job_prolang.to_sql('job_prolang', engine, if_exists='append', index=False)

968