In [ ]:
!pip install selenium webdriver-manager

In [ ]:
!pip install pandas

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import urllib.parse
import pandas as pd
import os
import time
import json
import datetime
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

In [ ]:

languages_data = {
  "Python": "Django, Flask, FastAPI, PyTorch",
    "Java": "Spring Boot, Hibernate, Struts",
    "JavaScript": "React, Vue, Node.js, Next.js",
    "C#": ".NET, Unity, Xamarin",
    "PHP": "Laravel, Symfony, CodeIgniter",
    "Visual Basic": "VBA, .NET Framework",
    "C++": "Qt, Boost, Unreal Engine,Embedded C, Win32 API",
    "SQL": "PostgreSQL, MySQL, T-SQL, SQL Server",  # merge into one
    "Delphi/Object Pascal": "VCL, FireMonkey",       # keep only one,
    "Assembly language": "NASM, MASM",
    "Swift": "SwiftUI, UIKit, Vapor",
    "Rust": "Rocket, Actix, Warp",
    "Fortran": "LAPACK, Scipy (Binding)",
    "MATLAB": "Simulink, Deep Learning Toolbox",
    "Kotlin": "Ktor, Spring Boot, Android Jetpack",
    "Ruby": "Ruby on Rails, Sinatra",
    "TypeScript": "Angular, NestJS, Svelte",
    "COBOL": "Mainframe Batch, CICS",
    "Scratch": "Block-based Programming",
    "Dart": "Flutter",
    "Julia": "Flux, Genie",
    "Lisp": "Common Lisp, Emacs Lisp",
    "Scala": "Akka, Play Framework, Spark",
    "Prolog": "SWI-Prolog",
    "Lua": "Löve, Roblox SDK",
    "Perl": "Catalyst, Dancer",
    "Objective-C": "Cocoa, Foundation",
    "Haskell": "Yesod, Servant",
    "VBScript": "ASP Classic, QTP",
    "F#": "Giraffe, Fable",
    "Groovy": "Grails, Gradle",
    "PL/SQL": "Oracle Database",
    "Transact-SQL": "MS SQL Server",
    "Classic Visual Basic": "VB6",
    "Erlang": "Phoenix (via Elixir), OTP",
    "Elixir": "Phoenix, Nerves",
    "Clojure": "Luminus, Ring",
    "Smalltalk": "Pharo, Seaside",
    "golang": "Gin, Echo, Fiber",
    "R-lang": "Tidyverse, Shiny, ggplot2",
    "Ada": "GNAT, Spark",
    "Logo": "Turtle Graphics",
    "ABAP": "SAP NetWeaver",
    "Scheme": "Racket, Guile",
    "Dlang": "Phobos, Vibe.d",
    "Apex": "Salesforce Framework",
    "Tcl": "Tk"
}
current_page = 0
data_all = []
for i, (lang,frame) in enumerate(languages_data.items()):
  framework_list = [f.strip() for f in frame.split(',')]
file_name = 'Final_Raw_data_HackerNews.json'
old_file = 'Raw_data_AddYear_HackerNews.json'

In [4]:
import json
current_page = 0
data_all = []
output_dir = '../raw_data'
output_path = os.path.join(output_dir, old_file)
os.path.exists(output_path)
with open(output_path, 'r', encoding='utf-8') as f:
    data_all = json.load(f)
print(f'Raw data: {len(data_all)} record')

Raw data: 35346 record

In [ ]:
# "C" : "Embedded C, Win32 API"
#   "Python": "Django, Flask, FastAPI, PyTorch",
#     "Java": "Spring Boot, Hibernate, Struts",
#     "JavaScript": "React, Vue, Node.js, Next.js",
#     "C#": ".NET, Unity, Xamarin",
#     "PHP": "Laravel, Symfony, CodeIgniter",
#     "Visual Basic": "VBA, .NET Framework",
#     "C++": "Qt, Boost, Unreal Engine,Embedded C, Win32 API",
#     "SQL": "PostgreSQL, MySQL, T-SQL",
#     "Assembly language": "NASM, MASM",
#     "SQL": "SQL Server, PostgreSQL",
#     "Swift": "SwiftUI, UIKit, Vapor",
#     "Rust": "Rocket, Actix, Warp",
#     "Fortran": "LAPACK, Scipy (Binding)",
#     "Delphi" : "VCL, FireMonkey", 
#     "MATLAB": "Simulink, Deep Learning Toolbox",
#     "Kotlin": "Ktor, Spring Boot, Android Jetpack",
#     "Ruby": "Ruby on Rails, Sinatra",
#     "TypeScript": "Angular, NestJS, Svelte",
#     "COBOL": "Mainframe Batch, CICS",
#     "Scratch": "Block-based Programming",
#     "Dart": "Flutter",  
#     "Julia": "Flux, Genie",
#     "Lisp": "Common Lisp, Emacs Lisp",
#     "Scala": "Akka, Play Framework, Spark",
#     "Prolog": "SWI-Prolog",
#     "Lua": "Löve, Roblox SDK",
#     "Perl": "Catalyst, Dancer",
#     "Objective-C": "Cocoa, Foundation",
#     "Haskell": "Yesod, Servant",
#     "VBScript": "ASP Classic, QTP",
#     "F#": "Giraffe, Fable",
#     "Groovy": "Grails, Gradle",
#     "PL/SQL": "Oracle Database",
#     "Transact-SQL": "MS SQL Server",
#     "Classic Visual Basic": "VB6",
#     "Erlang": "Phoenix (via Elixir), OTP",
#         "Elixir": "Phoenix, Nerves",
#         "Clojure": "Luminus, Ring",
#         "Smalltalk": "Pharo, Seaside",
#         "Golang": "Gin, Echo, Fiber",
#         "R-lang": "Tidyverse, Shiny, ggplot2",
#         "Ada": "GNAT, Spark",
#         "Logo": "Turtle Graphics",
#         "ABAP": "SAP NetWeaver",
#         "Scheme": "Racket, Guile",
#         "Dlang": "Phobos, Vibe.d",
#           "Apex": "Salesforce Framework",
#           "Tcl": "Tk"

In [5]:
for i, (lang,frame) in enumerate(languages_data.items()):
    while True:
        try:
            if lang == 'C':
                safe_lang = urllib.parse.quote('"C"')
                url = f'https://hn.algolia.com/?dateEnd=1770422400&dateRange=custom&dateStart=1609459200&page={current_page}&prefix=true&query=%{safe_lang}%&sort=byPopularity&type=story'
                
            elif (lang == 'C++') or (lang == 'C#') or (lang == 'F#'):
                safe_lang = urllib.parse.quote(lang)
                url = f'https://hn.algolia.com/?dateEnd=1770422400&dateRange=custom&dateStart=1609459200&page={current_page}&prefix=true&query=%{safe_lang}%&sort=byPopularity&type=story'
            else:
                url = f'https://hn.algolia.com/?dateEnd=1770422400&dateRange=custom&dateStart=1609459200&page={current_page}&prefix=true&query=%{lang}%&sort=byPopularity&type=story'
            
            # print("opening browser...")
            driver.get(url)
            time.sleep(5)

            container = driver.find_elements(By.CLASS_NAME, "Story_container")
            if not container:
                break
            
            time.sleep(5)
            for item in container:
                try:
                    title = item.find_element(By.CLASS_NAME, "Story_title").find_element(By.TAG_NAME, "a").text
                    meta_section = item.find_element(By.CLASS_NAME, "Story_meta")
                    time_text = meta_section.text
                    scraping_date = datetime.datetime.now()
                    data_all.append({"Title" : title, "language" : lang, "Years" : time_text, "Scraping_Date" : scraping_date})
                except Exception as e:
                    continue
                    
            if data_all:
                output_dir = '../raw_data'
                output_path = os.path.join(output_dir, file_name)
                os.makedirs(output_dir, exist_ok=True) 
                
                with open(output_path, 'w', encoding='utf-8') as f:
                    json.dump(data_all, f, indent=4, ensure_ascii=False, default=str)
                        
            current_page += 1
        except Exception as e:
            print(f"Error: {e}")
            break
            
    current_page = 0
    framework_list = [f.strip() for f in frame.split(',')]
    for fw in framework_list:
        if lang == 'C':
            c_fw_query = f'"{lang}" {fw}'
            new_key = urllib.parse.quote(c_fw_query)
            
        elif (lang == 'C++') or (lang == 'C#') or (lang == 'F#'):
            safe_lang = urllib.parse.quote(lang)
            new_key = safe_lang + " " + fw
        else:
            new_key = lang + " " + fw
            
        while True:
            try:
                url = f'https://hn.algolia.com/?dateEnd=1770422400&dateRange=custom&dateStart=1609459200&page={current_page}&prefix=true&query=%{new_key}%&sort=byPopularity&type=story'
                
                # print("opening browser...")
                driver.get(url)
                time.sleep(5)

                container = driver.find_elements(By.CLASS_NAME, "Story_container")
                if not container:
                    break
                
                time.sleep(5)
                for item in container:
                    try:
                        title = item.find_element(By.CLASS_NAME, "Story_title").find_element(By.TAG_NAME, "a").text
                        meta_section = item.find_element(By.CLASS_NAME, "Story_meta")
                        time_text = meta_section.text
                        scraping_date = datetime.datetime.now()
                        data_all.append({"Title" : title, "language" : lang, "Years" : time_text, "Scraping_Date" : scraping_date})
                    except Exception as e:
                        continue
                        
                if data_all:
                    output_dir = '../raw_data'
                    output_path = os.path.join(output_dir, file_name)
                    os.makedirs(output_dir, exist_ok=True) 
                    
                    with open(output_path, 'w', encoding='utf-8') as f:
                        json.dump(data_all, f, indent=4, ensure_ascii=False, default=str)
                            
                current_page += 1
            except Exception as e:
                print(f"Error: {e}")
                break
                
        current_page = 0
# df_raw_data = pd.DataFrame(data_all).drop_duplicates() #delete same row
# df_raw_data.to_json("Raw_data_HackerNews.json", orient='records', indent=4, force_ascii=False)
# print("Success to JSON file")

In [ ]:
if data_all:
        output_dir = '../raw_data'
        os.makedirs(output_dir, exist_ok=True) 
        output_path = os.path.join(output_dir, file_name)
                
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data_all, f, indent=4, ensure_ascii=False)

In [9]:
import pandas as pd
import os
import json
import datetime
import re

In [10]:
file_name = 'Raw_data_AddYear_HackerNews.json'
output_dir = '../raw_data'
os.makedirs(output_dir, exist_ok=True) 
output_path = os.path.join(output_dir, file_name)
with open(output_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
df_raw_data = pd.DataFrame(data)

In [11]:
df_raw_data.head()

,Title,language,Years,Scraping_Date
0,Uv is the best thing to happen to the Python e...,Python,2214 points|todsacerdoti|4 months ago|1324 com...,2026-03-05 07:24:44.130929
1,A from-scratch tour of Bitcoin in Python,Python,1208 points|yigitdemirag|5 years ago|277 comments,2026-03-05 07:24:44.296567
2,Python 3.13 Gets a JIT,Python,1081 points|todsacerdoti|2 years ago|521 comments,2026-03-05 07:24:44.446665
3,Show HN: I built a hardware processor that run...,Python,983 points|hwpythonner|10 months ago|265 comme...,2026-03-05 07:24:44.583786
4,Prettymaps: Small Python library to draw custo...,Python,982 points|sebg|5 years ago|74 comments,2026-03-05 07:24:44.811589

In [12]:
df_raw_data['Scrap_Year'] = pd.to_datetime(df_raw_data['Scraping_Date']).dt.year
df_raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 35346 entries, 0 to 35345
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          35346 non-null  str
 1   language       35346 non-null  str
 2   Years          35346 non-null  str
 3   Scraping_Date  35346 non-null  str
 4   Scrap_Year     35346 non-null  int32
dtypes: int32(1), str(4)
memory usage: 1.2 MB

In [13]:
time_info = df_raw_data['Years'].str.extract(r'(\d+)\s+(\w+)\s+ago')
df_raw_data['cleaned_year_comment'] = time_info[0].astype(float)
df_raw_data['unit_year'] = time_info[1]
display(df_raw_data.head())
print(df_raw_data.info())

,Title,language,Years,Scraping_Date,Scrap_Year,cleaned_year_comment,unit_year
0,Uv is the best thing to happen to the Python e...,Python,2214 points|todsacerdoti|4 months ago|1324 com...,2026-03-05 07:24:44.130929,2026,4.0,months
1,A from-scratch tour of Bitcoin in Python,Python,1208 points|yigitdemirag|5 years ago|277 comments,2026-03-05 07:24:44.296567,2026,5.0,years
2,Python 3.13 Gets a JIT,Python,1081 points|todsacerdoti|2 years ago|521 comments,2026-03-05 07:24:44.446665,2026,2.0,years
3,Show HN: I built a hardware processor that run...,Python,983 points|hwpythonner|10 months ago|265 comme...,2026-03-05 07:24:44.583786,2026,10.0,months
4,Prettymaps: Small Python library to draw custo...,Python,982 points|sebg|5 years ago|74 comments,2026-03-05 07:24:44.811589,2026,5.0,years

<class 'pandas.DataFrame'>
RangeIndex: 35346 entries, 0 to 35345
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 35346 non-null  str
 1   language              35346 non-null  str
 2   Years                 35346 non-null  str
 3   Scraping_Date         35346 non-null  str
 4   Scrap_Year            35346 non-null  int32
 5   cleaned_year_comment  35346 non-null  float64
 6   unit_year             35346 non-null  str
dtypes: float64(1), int32(1), str(5)
memory usage: 1.8 MB
None

In [14]:
df_raw_data.drop_duplicates(subset=['Title','language'], keep='first')
df_raw_data['cleaned_title'] = df_raw_data['Title'].str.strip()


def get_actual_year(row):
    val = row['cleaned_year_comment']
    unit = str(row['unit_year'])
    scrap_year = row['Scrap_Year']
    scrap_month = pd.to_datetime(row['Scraping_Date']).month
    
    if pd.isna(val): 
        return scrap_year
    if 'year' in unit:
        return scrap_year - int(val)
    elif 'month' in unit:
        if (scrap_month - int(val)) <= 0: 
            return scrap_year - 1
        else:
            return scrap_year 
    else:
        return scrap_year

df_raw_data['Actual_Post_Year'] = df_raw_data.apply(get_actual_year, axis=1).astype(int)

In [ ]:

df_final = df_raw_data[['cleaned_title','language','Scrap_Year','cleaned_year_comment','unit_year','Actual_Post_Year']]
df_final.head(2)

,cleaned_title,language,Scrap_Year,cleaned_year_comment,unit_year,Actual_Post_Year
0,Uv is the best thing to happen to the Python e...,Python,2026,4.0,months,2025
1,A from-scratch tour of Bitcoin in Python,Python,2026,5.0,years,2021

In [16]:
file_name = 'Cleaned_data_HackerNews.json'
output_dir = '../raw_data'
os.makedirs(output_dir, exist_ok=True) 
output_path = os.path.join(output_dir, file_name)

df_final.to_json(output_path, orient='records', force_ascii=False, indent=4)
print(f'Cleaned Data Found : {len(df_final)} records')

Cleaned Data Found : 35346 records

In [ ]:
import os
import json
import urllib.parse
import time
import datetime
from selenium.webdriver.common.by import By

# สมมติว่า driver และ languages_data ถูกประกาศไว้แล้ว

# 🌟 1. ตั้งค่า Time Slicing (ซอยเวลาทีละ 180 วัน / 6 เดือน)
start_timestamp = 1609459200  # 1 Jan 2021
end_timestamp = 1770422400    # สิ้นสุดโปรเจค (ประมาณปี 2026)
step = 15552000               # 180 วัน (คำนวณเป็นวินาที)

# สร้างลิสต์ของช่วงเวลา [ (start, end), (start, end), ... ]
time_chunks = []
current_ts = start_timestamp
while current_ts < end_timestamp:
    next_ts = min(current_ts + step, end_timestamp)
    time_chunks.append((current_ts, next_ts))
    current_ts = next_ts

data_all = []
file_name = 'Raw_data_Frameworks_Only_TimeSliced.json' # เซฟแยกไฟล์ จะได้ไม่ทับของเก่า

# 🌟 2. เริ่มลูปดึงเฉพาะ Framework (เก็บตก)
for i, (lang, frame) in enumerate(languages_data.items()):
    framework_list = [f.strip() for f in frame.split(',')]
    
    for fw in framework_list:
        # ใช้แค่ชื่อ Framework เพียวๆ ค้นหา
        new_key = urllib.parse.quote(fw)
        
        # 🌟 3. ลูปค้นหาตามช่วงเวลาทีละ 6 เดือน
        for start_t, end_t in time_chunks:
            current_page = 0
            
            while True:
                try:
                    # นำ start_t และ end_t ไปใส่ใน URL แบบไดนามิก
                    url = f'https://hn.algolia.com/?dateEnd={end_t}&dateRange=custom&dateStart={start_t}&page={current_page}&prefix=true&query=%{new_key}%&sort=byPopularity&type=story'
                    
                    driver.get(url)
                    time.sleep(5) # ให้เวลาเว็บโหลด

                    container = driver.find_elements(By.CLASS_NAME, "Story_container")
                    if not container:
                        break # ถ้าไม่มีกระทู้ในหน้านี้ (หรือหมดหน้า) ให้จบเพื่อขยับไป 6 เดือนถัดไป
                    
                    time.sleep(2)
                    for item in container:
                        try:
                            title = item.find_element(By.CLASS_NAME, "Story_title").find_element(By.TAG_NAME, "a").text
                            meta_section = item.find_element(By.CLASS_NAME, "Story_meta")
                            time_text = meta_section.text
                            scraping_date = datetime.datetime.now()
                            data_all.append({"Title" : title, "language" : lang, "Years" : time_text, "Scraping_Date" : scraping_date})
                        except Exception as e:
                            continue
                            
                    # เซฟข้อมูลทุกครั้งที่จบหน้า ป้องกันบอทพังกลางทาง
                    if data_all:
                        output_dir = '../raw_data'
                        output_path = os.path.join(output_dir, file_name)
                        os.makedirs(output_dir, exist_ok=True) 
                        
                        with open(output_path, 'w', encoding='utf-8') as f:
                            json.dump(data_all, f, indent=4, ensure_ascii=False, default=str)
                            
                    current_page += 1
                except Exception as e:
                    print(f"Error on {fw} ({start_t} to {end_t}): {e}")
                    break # ข้ามไปช่วงเวลาถัดไป